#!/bin/bash

# Windows on Travis does not obfuscate environment variables.
if [[ $TRAVIS_OS_NAME != "windows" ]]; then
	echo "Environment variables:"
	env | sort
fi

echo "SCM versions:"
if command -v bk; then bk --version; fi
if command -v hg; then hg --version; fi
if command -v git; then git --version; fi
if command -v svn; then svn --version; fi
if command -v cvs; then cvs --version; fi
if command -v mtn; then mtn --version; fi
if command -v bzr; then bzr version; fi
