.TH FOOBAR 1

.SH NAME

foobar \- general purpose utility

.SH SYNOPSIS

\fBfoobar\fP [\fIoptions\fP]

.SH DESCRIPTION

\fIfoobar\fP is a general purpose utility that does whatever you would
like it to do.

.SS Options
.TP
\fB-h, --help\fP
Helps you
.TP
\fB-V, --verbose\fP
Talks to you while doing whatever you would like it to do
.TP
\fB-n, --dry-run\fP
Only pretends to do whatever you would like it to do

.SH "SEE ALSO"
ls(1), rm(1), format(1M)
