
OSOLopengrok.pkg: 
	pkgmk -o -b /home/trond/source/package/data -d /home/trond/source/package/pkg OSOLopengrok
	pkgtrans -s /home/trond/source/package/pkg OSOLopengrok.pkg OSOLopengrok

clean:
	rm -rf pkg/OSOLopengrok.pkg pkg/OSOLopengrok

