INTRODUCE	pbray	1.1	Active	2009/01/22,09:32:39
##TITLE:  Introduced file
##ISSUE:	I...-..1     ++ISSUES++

EDIT_PROPS	pbray	1.1	Active	2009/01/22,09:32:54
##TITLE:  Edit file properties

CHECK-OUT	pbray	1.1	Active	2009/01/22,09:35:46
##TITLE:  Added a lint target
##NOTES: CHECKED OUT TO: /fileserver/sandbox/pbray/OpenGrokSampleRepository
##AUDIT: pbray 2009/01/22,09:35:46 1.1 Active CHECKED OUT TO: /fileserver/sandbox/pbray/OpenGrokSampleRepository/SimpleCProgram/Makefile 
##ISSUE:	I...-..2     ++ISSUES++

CHECK-IN	pbray	1.2	Active	2009/01/22,09:36:45
##TITLE:  Added a lint target
##NOTES: CHECKED IN FROM: /fileserver/sandbox/pbray/OpenGrokSampleRepository
##AUDIT: pbray 2009/01/22,09:36:45 1.2 Active CHECKED IN FROM: /fileserver/sandbox/pbray/OpenGrokSampleRepository/SimpleCProgram/Makefile 
##ISSUE:	I...-..2     ++ISSUES++

