name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - docker/README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description
      if: ${{ vars.DOCKER_SLUG != '' }}
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ vars.DOCKER_SLUG }}
        readme-filepath: ./docker/README.md
