# Copyright (c) 2026 - 2026, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

# Run Macaron's policies and generate Verification Summary Attestation reports.
# See https://github.com/oracle/macaron

name: Macaron check-github-actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  workflow_dispatch:
  schedule:
    - cron: "17 4 * * 1"

permissions:
  contents: read

jobs:
  macaron-check-github-actions:
    name: Macaron policy verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Check the GitHub Actions workflows in the repository for vulnerabilities.
        uses: oracle/macaron@4ddb55e3c9ef2c77b548be55c557078c4476fd9c # v0.24.0
        with:
          repo_path: ./
          policy_file: check-github-actions
          policy_purl: pkg:github.com/oracle/opengrok@.*
