name: Generate REST API documentation

on:
  push:
    paths:
      - openapi.yaml
      - .github/workflows/openapi.yml
      - dev/openapi.sh
    branches:
      - master
  pull_request:
    paths:
      - openapi.yaml
      - .github/workflows/openapi.yml
      - dev/openapi.sh

permissions:
  contents: write

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up JDK
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: 'oracle'
        java-version: '21'
    - name: Checkout gh-pages branch
      if: github.repository == 'oracle/opengrok'
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: gh-pages
        path: gh-pages
    - name: Refresh REST API doc
      env:
        OPENGROK_REPO_SLUG: ${{ github.repository }}
        OPENGROK_PULL_REQUEST: ${{ github.head_ref }}
        OPENGROK_REF: ${{ github.ref }}
        OPENGROK_BUILD_DIR: ${{ github.workspace }}
      run: ./dev/openapi.sh
